---

env:
    browser: true
    es6: true
    node: true

plugins:
    - '@typescript-eslint'

extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'prettier'

parser: '@typescript-eslint/parser'

settings:
    react:
        version: 'detect'

parserOptions:
    project: 'tsconfig.json'
    tsconfigRootDir: '.'
    ecmaFeatures:
        jsx: true
